services:
  php-devsecops:
    image: ghcr.io/pedrocorp/devsecops:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: devsecops
    ports:
      - "9300:80"
    environment:
      TAG: "your_tag"
      GIT_COMMIT: "your_commit_hash"
      GIT_URL: "your_git_url"
    volumes:
      - ./volume:/var/www/html/database
    restart: unless-stopped