services:
  php-devsecops:
    image: devsecops:1.0.0
    build:
      context: ../php-devops-tp
      dockerfile: Dockerfile
    container_name: php-devsecops
    ports:
      - "9300:80"
    environment:
      TAG: "your_tag"
      GIT_COMMIT: "your_commit_hash"
      GIT_URL: "your_git_url"
    volumes:
      - ./volume:/var/www/html/database
    restart: unless-stopped